// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQEPVbko-vK8L72pFSlDlrRvgreOm2cY',
    appId: '1:313737882209:web:804806899ae14e577d1820',
    messagingSenderId: '313737882209',
    projectId: 'flutter-facebook-e760f',
    authDomain: 'flutter-facebook-e760f.firebaseapp.com',
    storageBucket: 'flutter-facebook-e760f.appspot.com',
    measurementId: 'G-YC8J0M6383',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCikaUzFBe0rSbePr5_gWWX2vL9q605dkY',
    appId: '1:313737882209:android:9e453c25d091e3687d1820',
    messagingSenderId: '313737882209',
    projectId: 'flutter-facebook-e760f',
    storageBucket: 'flutter-facebook-e760f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS47wcAQjv6p-OipICc9rL1OwUxag0zVA',
    appId: '1:313737882209:ios:47d16787b0af81907d1820',
    messagingSenderId: '313737882209',
    projectId: 'flutter-facebook-e760f',
    storageBucket: 'flutter-facebook-e760f.appspot.com',
    iosBundleId: 'com.example.flutterFacebook',
  );
}
